openapi: 3.0.3
info:
  title: 'KH Shop API'
  description: 'API for Web Application Assignment Year 4'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/register:
    post:
      summary: 'Register the user'
      operationId: registerTheUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: rcborbbaospo
                  nullable: false
                lastName:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: vfpgh
                  nullable: false
                gender:
                  type: string
                  description: ''
                  example: female
                  nullable: false
                  enum:
                    - male
                    - female
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 50 characters.'
                  example: xwaelchi@example.net
                  nullable: false
                phoneNumber:
                  type: number
                  description: ''
                  example: 35491705.825686
                  nullable: false
                country:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: bahvcfnytjwgjntkyiovkgdhh
                  nullable: false
                city:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: mmbpm
                  nullable: false
                password:
                  type: string
                  description: 'Must match the regex /^.*(?=.{3,})(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\d\x])(?=.*[!$#%]).*$/. Must be at least 6 characters.'
                  example: pA~P/%
                  nullable: false
                profile:
                  type: string
                  description: ''
                  example: null
                  nullable: true
              required:
                - firstName
                - lastName
                - gender
                - email
                - phoneNumber
                - country
                - city
                - password
      security: []
  /api/verify-otp:
    post:
      summary: 'Verify OTP and log the user'
      operationId: verifyOTPAndLogTheUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
                  description: ''
                  example: voluptatem
                  nullable: false
                otpToken:
                  type: string
                  description: ''
                  example: voluptates
                  nullable: false
              required:
                - otp
                - otpToken
      security: []
  /api/login:
    post:
      summary: 'Login implementation'
      operationId: loginImplementation
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: hwisozk@example.net
                  nullable: false
                password:
                  type: string
                  description: ''
                  example: 'J-d$1{iaaX'
                  nullable: false
              required:
                - email
                - password
      security: []
  /api/logout:
    post:
      summary: 'Logout implementation'
      operationId: logoutImplementation
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/me:
    get:
      summary: 'Get current user'
      operationId: getCurrentUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/advertisement:
    get:
      summary: 'Display the listing of advertisement by take limit = 4'
      operationId: displayTheListingOfAdvertisementByTakeLimit4
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Advertisement not found'
                properties:
                  message:
                    type: string
                    example: 'Advertisement not found'
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Create a new advertisement'
      operationId: createANewAdvertisement
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: zkbja
                  nullable: false
                description:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: 'Et at saepe vel laborum.'
                  nullable: false
                order:
                  type: string
                  description: ''
                  example: sit
                  nullable: false
                image:
                  type: string
                  description: ''
                  example: corrupti
                  nullable: false
              required:
                - title
                - description
                - order
                - image
      security: []
  '/api/advertisement/{id}':
    get:
      summary: 'Get an advertisement'
      operationId: getAnAdvertisement
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No query results for model [App\Models\Advertisement] 13'
                properties:
                  message:
                    type: string
                    example: 'No query results for model [App\Models\Advertisement] 13'
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Edit an advertisement'
      operationId: editAnAdvertisement
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: 'n'
                  nullable: false
                description:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: 'Aut nemo voluptatem nostrum dolores totam accusamus eos.'
                  nullable: false
                order:
                  type: string
                  description: ''
                  example: vel
                  nullable: false
                image:
                  type: string
                  description: ''
                  example: ratione
                  nullable: false
              required:
                - title
                - description
                - order
                - image
      security: []
    delete:
      summary: ''
      operationId: deleteApiAdvertisementId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the advertisement.'
        example: 13
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
